name: puml-to-img
on:
  push:
    paths:
      - '**.puml'
jobs:
  puml-to-img:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: install plantuml
        run: |
          sudo apt install graphviz
          sudo apt install nodejs
          npm install -g node-plantuml

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5

      - name: convert files
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            if [[ $changed_file == *.puml ]]
            then
              puml generate $changed_file -o ${changed_file//.puml/.png}
              puml generate $changed_file --svg -o ${changed_file//.puml/.svg}
            fi
          done

      - name: commit & push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "rendered PNGs and SVGs" -a
          git push -u origin $GITHUB_REF
