name: render-puml
on:
  push:
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Generate PNG
      run: |
        pip install plantuml
        find ./meilenstein_03 -type f \( -iname "*.puml" \) -exec python -m plantuml {} \;
    - name: Generate SVG
      uses: grassedge/generate-plantuml-action@v1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
