name: render-plant-uml
on:
  push:
    # branches:
    #   - '*''
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: echo
        run: |
          echo "hElLo WoRlD"
