name: render-puml
on:
  push:
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: pip install
        run: pip install plantuml
      - name: run plantuml
        run: plantuml.py -h
