name: render-puml
on:
  push:
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: List PUML files
        run: find /meilenstein_03 -type f \( -iname "*.puml" \)
      # - name: run plantuml
      #   run: |
      #     pip install plantuml
      #     python -m plantuml | ls -R *.puml
