name: render-puml
on:
  push:
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Generate Plantuml
      uses: grassedge/generate-plantuml-action@v1.5
