name: render-puml
on:
  push:
    paths:
      - 'meilenstein_03/**'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run plantuml
        run: |
          pip install git+https://github.com/SamuelMarks/python-plantuml#egg=plantuml
          plantuml.py -h
